
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdpocdxvbhxxoxqkuwak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkcG9jZHh2Ymh4eG94cWt1d2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTQ4MTYsImV4cCI6MjA2Mjg5MDgxNn0.tdxjBCH2ZPCE-HXu3sKLSlFoDqcPvQb2JmDucTGWRm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
